apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: kubeflow
  name: "k8s-storage-pv-jupyter"
  labels:
    name: k8s-storage-pv-jupyter
    release: stable
spec:
  storageClassName: local-storage-jupyter
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /data/data3/k8s_storage_pv_jupyter
